var url=window.dict.url
var package_config_list='/package_config/package_config_load'
var target_url='/target_config/target_list'
var data_query_url='/dataquery'
var data_del_url='/datadel'
var data_commit_url='/datacommit'
var chart_query_url='/target_manager/chart_list'
var computer_agent_url='/computer_manager/computer_listen'
var ssh_check_url='/computer_manager/ssh_check'
export  {url,target_url,data_query_url,data_del_url,data_commit_url,chart_query_url,computer_agent_url,ssh_check_url}
